### PR TITLE
Change how inline data is handled

### LINKED ISSUE #178: Omitting of data type results in error with multi layer plots
Trying to plot several layers of errorband on one plot without explicitly setting the data type results in an error.

Minimal example:

DataFrame(q = 1:20, lb50 = 2, ub50 = 3, lb80 = 1, ub80 = 4) |> @vlplot() +
@vlplot(mark = {:errorband, color = :blue}, y = :lb80, y2= :ub80, x = :q) +
@vlplot(mark = {:errorband, color = :green}, y = :lb50, y2= :ub50, x = :q)

Error: Invalid field type “undefined”

As suggested by davidanthoff [here](https://discourse.julialang.org/t/overlaying-multiple-plots-in-vegalite/25945), this works:

DataFrame(q = 1:20, lb50 = 2, ub50 = 3, lb80 = 1, ub80 = 4) |> @vlplot() +
@vlplot(mark = {:errorband, color = :blue}, y = "lb80:q", y2= "ub80:q", x = "q:q") +
@vlplot(mark = {:errorband, color = :green}, y = "lb50:q", y2= "ub50:q", x = "q:q")

### LINKED ISSUE #229: Rework how inline data is handled
In particular, don't serialize at all in the `Dict` structure, but only when we write out to a string.

### PR DESCRIPTION
**Pull request by davidanthoff**
Fixes #229. Fixes #178.

In general this is only the start of a refactoring of the data story, with this new structure it should be easier to do a whole lot of other things down the road.

I think this should also reduce the memory footprint a bit.

### CODE REVIEW

File: src/vgspec.jl [hunk 1]
```diff
@@ -25,7 +29,6 @@ function (p::VGSpec)(data, name::String)
 
     it = IteratorInterfaceExtensions.getiterator(data)
     vg_set_spec_data!(new_dict, it, name)
-    detect_encoding_type!(new_dict, it)
```
Comment (davidanthoff) [inline src/vgspec.jl]: @mcmcgrath13 I believe you added that line originally. I don't think that ever did anything, right? Vega doesn't even have the encoding field, as far as I can tell, so I think this removal should be harmless? If not, let me know!
