### PR TITLE
Define functional setters using Setfield

### LINKED ISSUE #168: API to manipulate Vega Lite properties directly?
Is there a public interface to mutate Vega Lite properties?  For example, to change/add plot title, I know I can do

```julia
plt = @vlplot(...)
plt.params["title"] = "Title"
```

but it feels wrong since I'm guessing `.params` is an implementation detail.

If there are no easy way to change Vega Lite properties already, how about overloading `getproperty` and `setproperty!` so that you can simply modify properties?

```julia
plt.title = "Title"
```

One drawback in this approach is that there is no easy way to easily unset property.  But maybe setting `nothing` to clear out a field like

```julia
plt.config = nothing
```

is OK?

### PR DESCRIPTION
**Pull request by tkf**
With this PR, you can do:

```julia
julia> using VegaLite

julia> using Setfield  # to import `@set`

julia> plt = NamedTuple{(:x, :y)}.(tuple.(randn(1000), randn(1000))) |>
       @vlplot(
           :point,
           x=:x,
           y=:y,
       )

julia> plt2 = @set plt.mark = :line
```

This is built on top of #190 and will close #168.

### CODE REVIEW

**Comment by davidanthoff** [comment]
Cool, so this now is purely functional, with no mutation, right?

**Comment by tkf** [comment]
Yep, it's purely functional. Internally, Setfield uses something called lens which is invented by a Haskeller: https://github.com/ekmett/lens

**Comment by davidanthoff** [comment]
Alright, yes, then lets do this. Do you have to rebase now that #190 is merged, or do we merge this right away?

**Comment by tkf** [comment]
It looks like it has no conflict so it can be merged as-is? But let me know if you want me to rebase.

(I just restarted the CI for now.)

**Comment by davidanthoff** [comment]
The diff here on the PR looks weird: it looks like it will add `ObjectProxy`, but that is already on `master`, right? Slightly confused...

**Comment by tkf** [comment]
Oh, I wasn't looking at the diff. I rebased the PR.

File: src/spec_utils.jl [hunk 1]
```diff
@@ -32,3 +32,15 @@ function Base.getproperty(spec::ObjectLike, name::Symbol)
...
 end
+
+Setfield.set(spec::ObjectLike, ::typeof(@lens getparams(_)), params) =
+    typeof(spec)(params)
+
+function Setfield.set(spec::ObjectLike, ::PropertyLens{name}, value) where name
+    params = copy(getparams(spec))
+    params[keytype(params)(name)] = _maybeparams(value)
+    @set getparams(spec) = params
+end
```
Comment (tkf) [inline src/spec_utils.jl]: This could be written as `@set getparams(spec)[keytype(params)(name)] = value` if Base had `setindex` for `Dict`...: https://github.com/JuliaLang/julia/pull/33495

**Comment by davidanthoff** [comment]
Thanks, I really like this now! If you have time, maybe add some docs as another PR?

**Comment by tkf** [comment]
Will do.  Nice thing about Setfield is that it works with other constructs.  Things like

```julia
obj = (
    plt1 = @vlplot(...),
    plots = (
        @vlplot(...),
        @vlplot(...),
        @vlplot(...),
    ),
)

@set obj.plt1.mark = :point
@set obj.plots[2].mark = :line
@set last(obj.plots).mark = :line
```

should work now.

**Comment by davidanthoff** [comment]
Ok, that is pretty amazing!
